---
version: 2.1

orbs:
  slack: circleci/slack@3.4.2

parameters:
  publish:
    type: boolean
    default: false
  publish-type:
    type: string
    default: patch

_refs:
  defaults: &defaults
    working_directory: ~/cli
    docker:
      - image: node:12
  ssh-config: &ssh-config
    fingerprints:
      - ""
  restore_cache: &restore_cache
    keys:
      - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package.json"}}
      - v1-npm-{{checksum ".circleci/config.yml"}}
  gh-config: &gh-config
    name: Configuring GitHub
    command: |
      git config credential.helper 'cache --timeout=120'
      git config user.email "$GH_EMAIL"
      git config user.name "Release Bot"
  install: &install
    name: Install dependencies
    command: |
      npm --version
      node --version
      npm install
  test: &test
    name: Run tests
    command: npm run test

jobs:
  node-latest: &node-test
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: *install
      - run: *test
  node-12:
    <<: *node-test
    docker:
      - image: node:12
  cache:
    <<: *node-test
    steps:
      - checkout
      - run: *install
      - save_cache:
          key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package.json"}}
          paths:
            - ~/cli/node_modules

workflows:
  version: 2.1

  commit-workflow:
    unless: << pipeline.parameters.publish >>
    jobs:
      - node-latest
      - node-12
      - cache:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - node-latest
      - node-12
