name: version, tag and github release

on:
  push:
    branches: [main]

jobs:
  release:
    uses: salesforcecli/github-workflows/.github/workflows/githubRelease.yml@gbockus/updateReleaseToIncludeTokenInput
    with:
      githubToken: ${{ secrets.IDEE_GH_TOKEN }}
    secrets: inherit
